package org.apache.hadoop.hive.ql.abm.simulation;

public enum PredicateType {
  SINGLE_LESS_THAN,
  SINGLE_LESS_THAN_OR_EQUAL_TO,
  SINGLE_GREATER_THAN,
  SINGLE_GREATER_THAN_OR_EQUAL_TO,
  DOUBLE_LESS_THAN,
  DOUBLE_LESS_THAN_OR_EQUAL_TO,
  DOUBLE_GREATER_THAN,
  DOUBLE_GREATER_THAN_OR_EQUAL_TO
}
